### ISSUE TITLE
Warning about `depends_on` call when running `brew update`

### ISSUE THREAD

**Issue by cjwilburn** [rockyluke/homebrew-devops#3]
Hi,

When running `brew update` I get the following message for packages installed using this tap:
```
Warning: Calling 'depends_on :python3' is deprecated!
Use 'depends_on "python3"' instead.
/usr/local/Homebrew/Library/Taps/rockyluke/homebrew-devops/Formula/pip-pylint.rb:11:in `<class:PipPylint>'
Please report this to the rockyluke/devops tap!
```

I may be able to take a look and update these calls. If so, I'll add a PR that links to this issue. Thanks!

**Comment by rockyluke** [comment]
Thanks again.

**Comment by cjwilburn** [comment]
You're welcome. Thanks for providing these tools.
